{% set name = "pyFirmata" %}
{% set version = "1.0.2" %}
{% set sha256 = "81bc2704109161cee7c4c0544578be044a4be31d86fcb157c7bc53484015b634" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pyserial

test:
  imports:
    - pyfirmata

about:
  home: https://github.com/tino/pyFirmata
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'pyFirmata is a Python interface for the Firmata protocol.'

  dev_url: https://github.com/tino/pyFirmata

extra:
  recipe-maintainers:
    - abloemert
