{% set name = "pyFirmata" %}
{% set version = "1.0.1" %}
{% set sha256 = "f711056bacf7c8d5ceb822c3734883088f1c75ceaa0c2e924731aa523a029629" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pyserial

test:
  imports:
    - pyfirmata

about:
  home: https://github.com/tino/pyFirmata
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'pyFirmata is a Python interface for the Firmata protocol.'

  dev_url: https://github.com/tino/pyFirmata

extra:
  recipe-maintainers:
    - abloemert
