{% set name = "pyFirmata" %}
{% set version = "1.1.0" %}
{% set sha256 = "cc180d1b30c85a2bbca62c15fef1b871db048cdcfa80959968356d97bd3ff08e" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - pyserial

test:
  requires:
    - python {{ python_min }}
  imports:
    - pyfirmata

about:
  home: https://github.com/tino/pyFirmata
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'pyFirmata is a Python interface for the Firmata protocol.'

  dev_url: https://github.com/tino/pyFirmata

extra:
  recipe-maintainers:
    - abloemert
