travis:
  secure:
    BINSTAR_TOKEN: gjLOML+9rQDiExQTlfhTGiBmbJ/AGDNCZqFoqaPSERicXyW84E3q6W8J23m0TjXkHMmEcJolgqqn5d7iwT/RnGMe4UJ+TA7euASXjdcM5V4qWGO6DQdrSOhyFNHO4f08L3L9oEcZrnkGc+MDn80h5/2hLg2JjNWkJnlIsfgzTU1WKRgBHet0wPrzFEgTmNufPMAZEs02fRLZ+af57Wrrt0JjnVR33w5X1Gsm8oAqD31/WkLYeO5/kDIDJKoi4PiNmiwiA6VT13spZe2Wf/A4nOYsng7F0/vWFFCwJSz1ov3c8afDnrvHudDvLaUefC+Io7+IaFnYucsFKuum8y+jbgFUmHPLLFMBO4/X7g12HHuLc52PTgWDcfxZbdGgXHmiiiuhQJrRag2g9mYBE+3pNQYix5LMuBHGdV2yKl7gG4BjTDUoT/5NtebeL7wt1jGKQJMoAFPgTbDs5ktWXi47/RfqhWLEEBNknzXN/34vrX3ZQA06wbshphoYC//jTAnhsd5N4VCI+B9JGvP4fH58rO4wK1yLPHRUcXv+4vCB8oMsUjJZAM/6+JFU/FVmTssnVziuUcIe90aNZeoLEfSB6JgT39S7tjXQmRntCcCwebIXluFcTkO/95Y/yazsYVP02OZAhdw1n+kswn4v4qY0oG3NNva8geFhJZWNcB0UA/0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
