travis:
  secure:
    BINSTAR_TOKEN: NLwP1GG9XFJWtxiEgPfGQZCYSPjkBQ0Qsy1OUNXUGmKEAuY9r1wX1Vrnc8XDV7SUKG97+uJHr1R60JanPGm4HOxia09hRdgkYOFEkF8AcA+m3/CaciVGuZS4Xl+5btkeMDNuQIXHmH3Val00uqte26RrSnCc7381asrW905ZgIznts86OSWShOHGzeQCPgYKx8hgjvD+dJF3Xbe7mXg144wmLiV46dG+iIVDrqKY24UsZNjc9QkKigV6f9cjUQIQHIip5NVJZEdUaSU6xJ5yT8n2RF6QTeabMd7QtcLtEoWskYoG2iXi44L6Qbm99FtITW9nwBdaEu6TBI0rdPmp8cyH1sBnlUcQ4+PRoZDGHm2UWT1j6fDJVD9emryje+AscDLSTxJP8ok1olJhrjubwURXUxNoatJ2AnJKF1vJTIUjUjehQmqWgdazAjGYKPlZ7z4Q0/qzHE3aDorJD1wKbaE2I2lqeW8YH1o42ffHSuixvVw7KeGivQbN/lp5VuuSybnKxZldGVjHcDxXLhh3RKgdb/Mijl0HCaBfahew4q+EzvkQGRdMTlfHMTcN4j2MugIJDavP2YhESPQ9Qn5FmKQP6fq9N2yV4cJguBGS5t5jU3m9ccBVcJakrnO8sG1J5nIm144eRcGo4qFYPu1EY6wTr4yTBjZMco0tzp47hRE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
